Add API requests
PoMaKoM-RSTeam/Project-management pull request #4
Opened 2022-05-06 20:38 UTC by AlexXG0152

2022-05-07 05:47 UTC, Wolf-Den1994 reviewed
Don't forget fix error which appears when you use build 
And great work 👍

2022-05-07 05:47 UTC, Wolf-Den1994 commented on src/app/board/board-item/board-item.component.scss
> +//   padding-left: 7px;
Not needed comments

2022-05-07 05:47 UTC, Wolf-Den1994 commented on src/app/board/comment-item/comment-item.component.scss
> +  // border: 1px solid rgba(223, 223, 223, 0.37);
Comment

2022-05-07 05:47 UTC, Wolf-Den1994 commented on src/app/services/error.interceptor.ts
> +        console.log(errorMessage);
If you want to send error to console, please use for it `console.log`

2022-05-07 05:47 UTC, Wolf-Den1994 commented on src/app/services/error.interceptor.ts
> +        console.log(errorMessage);
You can add message from ng-zorro for send message for user
https://ng.ant.design/components/message/en
But only, if you want :)

2022-05-07 05:47 UTC, Wolf-Den1994 commented on src/app/space/components/list/list.component.ts
> +    //   console.log(data);
Comment

2022-05-07 10:50 UTC, Wolf-Den1994 commented on angular.json
>            "defaultConfiguration": "development"
возможно эти строчки с прокси нужно добавить и для продакшен

2022-05-07 11:30 UTC, algolj requested changes
Correct all remarks from Wolf-Den1994. All is well except for them.

2022-05-08 11:42 UTC, Wolf-Den1994 commented on angular.json
>            "defaultConfiguration": "development"
не нужно, проект тогда вообще не собирается

2022-05-08 19:51 UTC, Wolf-Den1994 approved these changes

2022-05-08 20:28 UTC, algolj approved these changes
Смысла особо чекать небыло, ты сам все пофиксил )

2022-05-09 05:43 UTC, merged